### ISSUE TITLE
upgrade logcore requirements to be compatible with latest version too...

### ISSUE THREAD

**Issue by Zorono** [maddinat0r/samp-log#12]

**Comment by maddinat0r** [comment]
Done in f2b725ba5ee74bb43db59180fd9c25ddef7ff011.

**Comment by TemaSM** [comment]
@maddinat0r this issue got actual state, because `samp-log` need to be updated to use `v0.5.2` of `log-core`

**Comment by maddinat0r** [comment]
You can always download the latest log-core version [here](https://github.com/maddinat0r/samp-log-core/releases), and replace the old `log-core2.so`/`log-core2.dll` file with the newer one.
