### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by Dayvison** [maddinat0r/samp-log#2]
What is needed to load this plugin, i have 
http://prntscr.com/biwpbc
installed.

```
Server Plugins
--------------
 Loading plugin: crashdetect
  CrashDetect v4.15.1 is OK.
  Loaded.
 Loading plugin: streamer


*** Streamer Plugin v2.7.8 by Incognito loaded ***

  Loaded.
 Loading plugin: filemanager
******************
** FILE MANAGER **
**    Loaded    **
** Version 1.5 **
******************
  Loaded.
 Loading plugin: sscanf


 ===============================

      sscanf plugin loaded.

   (c) 2009 Alex "Y_Less" Cole

   0.3d-R2 500 Players "dnee"

 ===============================

  Loaded.
 Loading plugin: timerfix
  >> TimerFix v1.5 successfully loaded.
  Loaded.
 Loading plugin: log-plugin
  Failed.
 Loaded 5 plugins.


Started server on port: 7777, with maxplayers: 50 lanmode is OFF.
```

**Comment by maddinat0r** [comment]
You are missing some more recent VC redistributions. Make sure you run Windows Updates.
If that still doesn't resolve your problem, [install the UCRT](https://www.microsoft.com/en-US/download/details.aspx?id=48234) and the [VC 2015 redistributables](https://www.microsoft.com/en-US/download/details.aspx?id=48145) (you need the **x86** download).

**Comment by GAMESTERVIRUS** [comment]
how to install i downloaded but there too much files which one to install??

**Comment by GAMESTERVIRUS** [comment]
bro what to do i installed this files previously and am not able to install windows ucrt how to fix the prob
