### ISSUE TITLE
[ incompatibility] samp-log and mysql_plugin

### ISSUE THREAD

**Issue by Tyrar** [maddinat0r/samp-log#3]
Hello,

This afternoon, I tried to use _samp-log_ in a project contening _a_mysql_. However, there is a small bug with E_LOGLEVEL enumeration (it is already declared and LOG_INFO doesn't exist in a_mysql).

In _a_mysql.inc_ :

``` pawn
enum E_LOGLEVEL
{
    LOG_NONE = 0,
    LOG_ERROR = 1,
    LOG_WARNING = 2,
    LOG_DEBUG = 4,

    LOG_ALL = LOG_ERROR | LOG_WARNING | LOG_DEBUG
};
```

In _samp-log.inc_ :

``` pawn
enum E_LOGLEVEL
{
    NONE = 0,
    DEBUG = 1,
    INFO = 2,
    WARNING = 4,
    ERROR = 8,

    ALL = ERROR | WARNING | INFO | DEBUG
};
```

For the next version, is it possible to correct this ?

**Comment by maddinat0r** [comment]
Thanks for reporting!
I'm aware of this and have already fixed the enum in pBlueG/SA-MP-MySQL@aa1b912225ce6041b95d9339774769cefa5ad1b8. So this is more of a MySQL plugin problem than a log plugin one. I'm going to release a small update which includes that fix in the following days.
