### ISSUE TITLE
function to print logs to console

### ISSUE THREAD

**Issue by maddinat0r** [maddinat0r/samp-log#4]
I should add some kind of feature/function which allows for specific loggers to also print their log lines directly to console.

**Comment by spacemud** [comment]
I'd like this - what about an option to just log to stdout only without file logging?

**Comment by maddinat0r** [comment]
Implemented in maddinat0r/samp-log-core#7.

@spacemud I thought about adding a sink feature, where you can specify a custom destination and format for log messages. But that's just a thought, so don't expect that feature very soon.
