### ISSUE TITLE
sampctl: Add .inc file into the repo

### ISSUE THREAD

**Issue by ziggi** [maddinat0r/samp-log#9]
For now `sampctl` isn't working, because `.inc` file is not existed in the repo (only `.inc.in`), so it would be nice to add `.inc` file into the repo.

```
(fatal) cannot read from file: "log-plugin"
```
Or it's a sampctl issue...

**Comment by maddinat0r** [comment]
The include file should be taken from the packaged download. The package definition file should be okay, so it's probably a sampctl bug.
I'll close this for now, but feel free to reopen this if you think there's actually a problem with the `pawn.json` file itself here.

**Comment by ziggi** [comment]
Yes, I has ask Southclaws about it and he say what it is a sampctl problem. I just forgot to close the issue.
